/**
 * Street Park Now — Backend
 * Claude-powered NYC parking intelligence
 */

require("dotenv").config();
const express = require("express");
const cors    = require("cors");
const cron    = require("node-cron");
const { Pool }  = require("pg");
const Stripe    = require("stripe");
const twilio    = require("twilio");
const crypto    = require("crypto");

const app  = express();
const PORT = process.env.PORT || 3001;

const stripe       = new Stripe(process.env.STRIPE_SECRET_KEY);
const twilioClient = twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN);
const db           = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

const JWT_SECRET = process.env.JWT_SECRET || "movemycar-secret-change-in-prod";

// Simple JWT implementation without external dependency
function signToken(payload) {
  const header = Buffer.from(JSON.stringify({ alg:"HS256", typ:"JWT" })).toString("base64url");
  const body   = Buffer.from(JSON.stringify({ ...payload, iat: Math.floor(Date.now()/1000) })).toString("base64url");
  const sig    = crypto.createHmac("sha256", JWT_SECRET).update(`${header}.${body}`).digest("base64url");
  return `${header}.${body}.${sig}`;
}

function verifyToken(token) {
  try {
    const [header, body, sig] = token.split(".");
    const expected = crypto.createHmac("sha256", JWT_SECRET).update(`${header}.${body}`).digest("base64url");
    if (sig !== expected) return null;
    return JSON.parse(Buffer.from(body, "base64url").toString());
  } catch { return null; }
}

function authMiddleware(req, res, next) {
  const token = req.headers.authorization?.replace("Bearer ", "");
  if (!token) return res.status(401).json({ error: "Not authenticated" });
  const payload = verifyToken(token);
  if (!payload) return res.status(401).json({ error: "Invalid token" });
  req.userId = payload.userId;
  req.userTier = payload.tier;
  next();
}

// Tier limits
const TIER_LIMITS = {
  free:      { searches: 8,    savedSearches: 0,  recentOnMap: 0  },
  basic:     { searches: 999,  savedSearches: 0,  recentOnMap: 2  },
  premium:   { searches: Infinity, savedSearches: 0, recentOnMap: 2 },
  unlimited: { searches: Infinity, savedSearches: 10, recentOnMap: 2 },
};

app.use(cors({ origin: "*" }));
app.use("/webhook", express.raw({ type: "application/json" }));
app.use(express.json());

const SOCRATA = "https://data.cityofnewyork.us/resource";

// ─── CLAUDE ───────────────────────────────────────────────────────────────────
async function askClaude(prompt, maxTokens = 1500) {
  const r = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY || "",
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-opus-4-5",
      max_tokens: maxTokens,
      messages: [{ role: "user", content: prompt }],
    }),
  });
  if (!r.ok) throw new Error(`Claude API ${r.status}`);
  const d = await r.json();
  return d.content?.[0]?.text || "";
}

// ─── HEALTH ───────────────────────────────────────────────────────────────────
app.get("/health", (req, res) => res.json({ ok: true, ts: new Date().toISOString() }));

// ─── HELPERS ──────────────────────────────────────────────────────────────────
function parseSignText(text) {
  if (!text) return null;
  const upper = text.toUpperCase();
  if (!upper.includes("STREET CLEANING") && !upper.includes("NO PARKING")) return null;
  const dayMap = { MON:"Mon", TUE:"Tue", WED:"Wed", THU:"Thu", FRI:"Fri", SAT:"Sat", SUN:"Sun" };
  const days = Object.entries(dayMap).filter(([k]) => new RegExp(`\\b${k}`,"i").test(text)).map(([,v]) => v);
  const tm = text.match(/(\d{1,2}(?::\d{2})?\s*(?:AM|PM)?)\s*(?:[-]|TO|THRU)\s*(\d{1,2}(?::\d{2})?\s*(?:AM|PM)?)/i);
  return { days, time: tm ? `${tm[1].trim()} - ${tm[2].trim()}` : null, raw: text };
}

function dedupe(arr) {
  const seen = new Set();
  return arr.filter(r => { const k = `${r.days}-${r.time}-${r.side}`; return seen.has(k) ? false : seen.add(k); });
}

function haversineKm(lat1, lng1, lat2, lng2) {
  const R = 6371, dLat = (lat2-lat1)*Math.PI/180, dLng = (lng2-lng1)*Math.PI/180;
  const a = Math.sin(dLat/2)**2 + Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLng/2)**2;
  return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));
}

// ─── NEIGHBORHOOD STREET CATALOG ─────────────────────────────────────────────
// Hardcoded verified streets for major neighborhoods — instant, reliable
const NEIGHBORHOOD_STREETS = {
  // NYC - Brooklyn
  "williamsburg": ["BEDFORD AVENUE","BERRY STREET","BROADWAY","DIVISION AVENUE","DRIGGS AVENUE","FLUSHING AVENUE","FROST STREET","GRAND STREET","HAVEMEYER STREET","HOOPER STREET","KENT AVENUE","LEE AVENUE","LORIMER STREET","LYNCH STREET","MANHATTAN AVENUE","MARCY AVENUE","METROPOLITAN AVENUE","MONTROSE AVENUE","MOORE STREET","MYRTLE AVENUE","NORTH 1 STREET","NORTH 10 STREET","NORTH 11 STREET","NORTH 12 STREET","NORTH 3 STREET","NORTH 4 STREET","NORTH 5 STREET","NORTH 6 STREET","NORTH 7 STREET","NORTH 8 STREET","NORTH 9 STREET","PENN STREET","PETERSFIELD STREET","POWERS STREET","ROEBLING STREET","SOUTH 1 STREET","SOUTH 2 STREET","SOUTH 3 STREET","SOUTH 4 STREET","SOUTH 5 STREET","SOUTH 8 STREET","UNION AVENUE","VARET STREET","WALTON STREET","WHIPPLE STREET","WILSON STREET","WITHERS STREET","WYTHE AVENUE"],
  "brooklyn heights": ["ATLANTIC AVENUE","CLARK STREET","COLUMBIA HEIGHTS","CRANBERRY STREET","FULTON STREET","GRACE COURT","GRACE COURT ALLEY","HENRY STREET","HICKS STREET","JORALEMON STREET","LOVE LANE","MIDDAGH STREET","MONTAGUE STREET","MONTAGUE TERRACE","ORANGE STREET","PIERREPONT PLACE","PIERREPONT STREET","PINEAPPLE STREET","POPLAR STREET","REMSEN STREET","VINE STREET","WILLOW PLACE","WILLOW STREET"],
  "park slope": ["1 STREET","2 STREET","3 STREET","4 STREET","5 STREET","6 STREET","7 STREET","8 STREET","9 STREET","BERKELEY PLACE","CARROLL STREET","DEGRAW STREET","EAST DRIVE","FIFTH AVENUE","FLATBUSH AVENUE","GARFIELD PLACE","LINCOLN PLACE","MONTGOMERY PLACE","PARK PLACE","PLAZA STREET WEST","POLHEMUS PLACE","PRESIDENT STREET","PROSPECT PARK WEST","SAINT JOHNS PLACE","SEVENTH AVENUE","SIXTH AVENUE","STERLING PLACE","UNION STREET","WARREN STREET","WINDSOR PLACE"],
  "greenpoint": ["ASH STREET","BOX STREET","CALYER STREET","EAGLE STREET","FREEMAN STREET","GREENPOINT AVENUE","HURON STREET","INDIA STREET","JAVA STREET","KENT STREET","KINGSLAND AVENUE","LORIMER STREET","MANHATTAN AVENUE","MCGUINNESS BOULEVARD","MESEROLE AVENUE","MONITOR STREET","MOULTRIE STREET","NASSAU AVENUE","NEWEL STREET","NOBLE STREET","NORMAN AVENUE","PROVOST STREET","RICHARDSON STREET","RUSSELL STREET","VAN DAM STREET","WEST STREET"],
  "bushwick": ["BLEECKER STREET","BROADWAY","BUSHWICK AVENUE","CENTRAL AVENUE","CORNELIA STREET","DEKALB AVENUE","ELDERT STREET","EVERGREEN AVENUE","FLUSHING AVENUE","FOREST STREET","GATES AVENUE","GROVE STREET","HART STREET","HIMROD STREET","IRVING AVENUE","JEFFERSON STREET","KNICKERBOCKER AVENUE","LINDEN STREET","MADISON STREET","MELROSE STREET","MOFFAT STREET","MORGAN AVENUE","SCHAEFER STREET","STOCKHOLM STREET","STANHOPE STREET","TROUTMAN STREET","WILSON AVENUE","WEIRFIELD STREET"],
  "dumbo": ["ADAMS STREET","ANCHORAGE PLACE","BRIDGE STREET","CONCORD STREET","DOCK STREET","FERRY STREET","FRONT STREET","FULTON STREET","GOLD STREET","JAY STREET","JOHN STREET","MAIN STREET","MARSHALL STREET","MIDDAGH STREET","PEARL STREET","PLYMOUTH STREET","PROSPECT STREET","SANDS STREET","WATER STREET","WASHINGTON STREET"],
  "cobble hill": ["AMITY STREET","ATLANTIC AVENUE","BALTIC STREET","BOURUM PLACE","CHEEVER PLACE","CLINTON STREET","CONGRESS STREET","DEGRAW STREET","HENRY STREET","HICKS STREET","KANE STREET","PACIFIC STREET","PRESIDENT STREET","STRONG PLACE","TOMPKINS PLACE","WARREN STREET","WYCKOFF STREET"],
  "carroll gardens": ["1 PLACE","2 PLACE","3 PLACE","4 PLACE","ATLANTIC AVENUE","BALTIC STREET","CLINTON STREET","COURT STREET","DEGRAW STREET","HENRY STREET","HUNTINGTON STREET","LUQUER STREET","NELSON STREET","PRESIDENT STREET","SACKETT STREET","SMITH STREET","UNION STREET","WARREN STREET","WYCKOFF STREET"],
  "bed stuy": ["AUBURN PLACE","BAINBRIDGE STREET","BEDFORD AVENUE","BROADWAY","CHAUNCEY STREET","CLIFTON PLACE","DECATUR STREET","DEKALB AVENUE","FULTON STREET","GATES AVENUE","GREENE AVENUE","HALSEY STREET","HANCOCK STREET","HART STREET","JEFFERSON AVENUE","KOSCIUSZKO STREET","LAFAYETTE AVENUE","LEX AVENUE","LEWIS AVENUE","LEXINGTON AVENUE","MACON STREET","MACDONOUGH STREET","MADISON STREET","MARCUS GARVEY BOULEVARD","MONROE STREET","NOSTRAND AVENUE","PUTNAM AVENUE","REID AVENUE","SARATOGA AVENUE","STUYVESANT AVENUE","SUMNER AVENUE","THROOP AVENUE","TOMPKINS AVENUE","VAN BUREN STREET","WEIRFIELD STREET"],
  // NYC - Manhattan
  "west village": ["BANK STREET","BARROW STREET","BEDFORD STREET","BETHUNE STREET","CHARLES STREET","CHRISTOPHER STREET","CLARKSON STREET","COMMERCE STREET","CORNELIA STREET","GROVE STREET","HORATIO STREET","HUDSON STREET","JANE STREET","LEROY STREET","MORTON STREET","PERRY STREET","WASHINGTON STREET","WAVERLY PLACE","WEST 10 STREET","WEST 11 STREET","WEST 12 STREET","WEST 13 STREET","WEST 4 STREET","WEST STREET","WEEHAWKEN STREET"],
  "east village": ["1 AVENUE","2 AVENUE","3 AVENUE","AVENUE A","AVENUE B","AVENUE C","AVENUE D","EAST 10 STREET","EAST 11 STREET","EAST 12 STREET","EAST 13 STREET","EAST 14 STREET","EAST 1 STREET","EAST 2 STREET","EAST 3 STREET","EAST 4 STREET","EAST 5 STREET","EAST 6 STREET","EAST 7 STREET","EAST 8 STREET","EAST 9 STREET","SAINT MARKS PLACE","STUYVESANT STREET","TOMPKINS SQUARE"],
  "greenwich village": ["6 AVENUE","7 AVENUE SOUTH","BARROW STREET","BEDFORD STREET","BLEECKER STREET","CHRISTOPHER STREET","CORNELIA STREET","DOWNING STREET","GROVE STREET","HUDSON STREET","JANE STREET","JONES STREET","KING STREET","LEROY STREET","MACDOUGAL STREET","MINETTA LANE","MINETTA STREET","MORTON STREET","PERRY STREET","PRINCE STREET","SULLIVAN STREET","THOMPSON STREET","WASHINGTON SQUARE EAST","WASHINGTON SQUARE NORTH","WASHINGTON SQUARE SOUTH","WASHINGTON SQUARE WEST","WAVERLY PLACE","WEST 10 STREET","WEST 11 STREET","WEST 12 STREET","WEST 13 STREET","WEST 14 STREET","WEST 3 STREET","WEST 4 STREET","WEST 8 STREET","WEST 9 STREET"],
  "soho": ["BROADWAY","BROOME STREET","CANAL STREET","CROSBY STREET","GRAND STREET","GREENE STREET","HOWARD STREET","HOUSTON STREET","KING STREET","LAGUARDIA PLACE","MERCER STREET","PRINCE STREET","SPRING STREET","SULLIVAN STREET","THOMPSON STREET","VANDAM STREET","WEST BROADWAY","WOOSTER STREET"],
  "tribeca": ["AVENUE OF THE AMERICAS","BEACH STREET","BROADWAY","CANAL STREET","CHAMBERS STREET","CHURCH STREET","DESBROSSES STREET","DUANE STREET","FRANKLIN STREET","GREENWICH STREET","HARRISON STREET","HUDSON STREET","JAY STREET","LAIGHT STREET","LEONARD STREET","LISPENARD STREET","MOORE STREET","MURRAY STREET","N MOORE STREET","READE STREET","STAPLE STREET","THOMAS STREET","VESTRY STREET","WALKER STREET","WARREN STREET","WASHINGTON STREET","WATTS STREET","WHITE STREET","WORTH STREET"],
  "hell's kitchen": ["10 AVENUE","11 AVENUE","8 AVENUE","9 AVENUE","WEST 42 STREET","WEST 43 STREET","WEST 44 STREET","WEST 45 STREET","WEST 46 STREET","WEST 47 STREET","WEST 48 STREET","WEST 49 STREET","WEST 50 STREET","WEST 51 STREET","WEST 52 STREET","WEST 53 STREET","WEST 54 STREET","WEST 55 STREET","WEST 56 STREET","WEST 57 STREET","WEST 58 STREET","WEST 59 STREET"],
  "upper west side": ["AMSTERDAM AVENUE","BROADWAY","CENTRAL PARK WEST","COLUMBUS AVENUE","RIVERSIDE DRIVE","WEST END AVENUE","WEST 59 STREET","WEST 60 STREET","WEST 61 STREET","WEST 62 STREET","WEST 63 STREET","WEST 64 STREET","WEST 65 STREET","WEST 66 STREET","WEST 67 STREET","WEST 68 STREET","WEST 69 STREET","WEST 70 STREET","WEST 71 STREET","WEST 72 STREET","WEST 73 STREET","WEST 74 STREET","WEST 75 STREET","WEST 76 STREET","WEST 77 STREET","WEST 78 STREET","WEST 79 STREET","WEST 80 STREET","WEST 81 STREET","WEST 82 STREET","WEST 83 STREET","WEST 84 STREET","WEST 85 STREET","WEST 86 STREET","WEST 87 STREET","WEST 88 STREET","WEST 89 STREET","WEST 90 STREET","WEST 91 STREET","WEST 92 STREET","WEST 93 STREET","WEST 94 STREET","WEST 95 STREET","WEST 96 STREET","WEST 97 STREET","WEST 98 STREET","WEST 99 STREET","WEST 100 STREET"],
  "upper east side": ["1 AVENUE","2 AVENUE","3 AVENUE","5 AVENUE","EAST 59 STREET","EAST 60 STREET","EAST 61 STREET","EAST 62 STREET","EAST 63 STREET","EAST 64 STREET","EAST 65 STREET","EAST 66 STREET","EAST 67 STREET","EAST 68 STREET","EAST 69 STREET","EAST 70 STREET","EAST 71 STREET","EAST 72 STREET","EAST 73 STREET","EAST 74 STREET","EAST 75 STREET","EAST 76 STREET","EAST 77 STREET","EAST 78 STREET","EAST 79 STREET","EAST 80 STREET","EAST 81 STREET","EAST 82 STREET","EAST 83 STREET","EAST 84 STREET","EAST 85 STREET","EAST 86 STREET","EAST 87 STREET","EAST 88 STREET","EAST 89 STREET","EAST 90 STREET","EAST 91 STREET","EAST 92 STREET","EAST 93 STREET","EAST 94 STREET","EAST 95 STREET","EAST 96 STREET","LEXINGTON AVENUE","MADISON AVENUE","PARK AVENUE","YORK AVENUE"],
  "harlem": ["ADAM CLAYTON POWELL JR BOULEVARD","AMSTERDAM AVENUE","BRADHURST AVENUE","BROADWAY","CONVENT AVENUE","EDGECOMBE AVENUE","EIGHTH AVENUE","FREDERICK DOUGLASS BOULEVARD","HAMILTON TERRACE","LENOX AVENUE","LEXINGTON AVENUE","MADISON AVENUE","MANHATTAN AVENUE","MORNINGSIDE AVENUE","NICHOLAS AVENUE","PARK AVENUE","SAINT NICHOLAS AVENUE","SEVENTH AVENUE","STRIVERS ROW","WEST 110 STREET","WEST 111 STREET","WEST 112 STREET","WEST 113 STREET","WEST 114 STREET","WEST 115 STREET","WEST 116 STREET","WEST 117 STREET","WEST 118 STREET","WEST 119 STREET","WEST 120 STREET","WEST 121 STREET","WEST 122 STREET","WEST 123 STREET","WEST 124 STREET","WEST 125 STREET","WEST 126 STREET","WEST 127 STREET","WEST 128 STREET","WEST 129 STREET","WEST 130 STREET"],
  "chelsea": ["10 AVENUE","11 AVENUE","8 AVENUE","9 AVENUE","WEST 14 STREET","WEST 15 STREET","WEST 16 STREET","WEST 17 STREET","WEST 18 STREET","WEST 19 STREET","WEST 20 STREET","WEST 21 STREET","WEST 22 STREET","WEST 23 STREET","WEST 24 STREET","WEST 25 STREET","WEST 26 STREET","WEST 27 STREET","WEST 28 STREET","WEST 29 STREET"],
  "lower east side": ["ALLEN STREET","ATTORNEY STREET","BROOME STREET","CANAL STREET","CHRYSTIE STREET","CLINTON STREET","DELANCEY STREET","ELDRIDGE STREET","ESSEX STREET","FORSYTH STREET","GRAND STREET","HESTER STREET","HOUSTON STREET","LUDLOW STREET","MADISON STREET","MONROE STREET","NORFOLK STREET","ORCHARD STREET","PITT STREET","RIVINGTON STREET","RUTGERS STREET","STANTON STREET","SUFFOLK STREET","WILLET STREET"],
  "financial district": ["BATTERY PLACE","BEEKMAN STREET","BOWLING GREEN","BROADWAY","CEDAR STREET","CORTLANDT STREET","DEY STREET","EXCHANGE PLACE","FULTON STREET","GOLD STREET","JOHN STREET","LIBERTY STREET","MAIDEN LANE","NASSAU STREET","NEW STREET","PEARL STREET","PINE STREET","RECTOR STREET","STONE STREET","WALL STREET","WATER STREET","WHITEHALL STREET","WILLIAM STREET"],
  "gramercy park": ["1 AVENUE","2 AVENUE","3 AVENUE","EAST 14 STREET","EAST 15 STREET","EAST 16 STREET","EAST 17 STREET","EAST 18 STREET","EAST 19 STREET","EAST 20 STREET","EAST 21 STREET","EAST 22 STREET","EAST 23 STREET","EAST 24 STREET","EAST 25 STREET","GRAMERCY PARK EAST","GRAMERCY PARK NORTH","GRAMERCY PARK SOUTH","GRAMERCY PARK WEST","IRVING PLACE","LEXINGTON AVENUE","PARK AVENUE SOUTH","STUYVESANT SQUARE"],
  "midtown": ["5 AVENUE","6 AVENUE","7 AVENUE","8 AVENUE","BROADWAY","EAST 42 STREET","EAST 43 STREET","EAST 44 STREET","EAST 45 STREET","EAST 46 STREET","EAST 47 STREET","EAST 48 STREET","EAST 49 STREET","EAST 50 STREET","LEXINGTON AVENUE","MADISON AVENUE","PARK AVENUE","VANDERBILT AVENUE","WEST 42 STREET","WEST 43 STREET","WEST 44 STREET","WEST 45 STREET","WEST 46 STREET","WEST 47 STREET","WEST 48 STREET","WEST 49 STREET","WEST 50 STREET"],
  // NYC - Queens
  "astoria": ["21 STREET","23 STREET","29 STREET","31 STREET","33 STREET","35 STREET","36 AVENUE","37 AVENUE","38 AVENUE","ASTORIA BOULEVARD","BROADWAY","DITMARS BOULEVARD","HOYT AVENUE NORTH","HOYT AVENUE SOUTH","NEWTOWN AVENUE","NORTHERN BOULEVARD","STEINWAY STREET","VERMONT PLACE"],
  "long island city": ["21 STREET","22 STREET","23 STREET","24 STREET","44 DRIVE","44 ROAD","45 AVENUE","45 ROAD","46 AVENUE","47 AVENUE","48 AVENUE","BORDEN AVENUE","COURT SQUARE","DAVIS STREET","DUTCH KILLS STREET","JACKSON AVENUE","NORTHERN BOULEVARD","PURVES STREET","QUEENS BOULEVARD","QUEENS PLAZA NORTH","QUEENS PLAZA SOUTH","SKILLMAN AVENUE","THOMPSON AVENUE","THOMSON AVENUE","VERNON BOULEVARD","VAN DAM STREET","WATER STREET","YOUNG STREET"],
  "flushing": ["BOWNE STREET","CHERRY AVENUE","COLLEGE POINT BOULEVARD","ELM AVENUE","FRANKLIN AVENUE","GERANIUM AVENUE","HOLLY AVENUE","KISSENA BOULEVARD","LINDEN PLACE","MAIN STREET","MAPLE AVENUE","MURRAY STREET","NORTHERN BOULEVARD","PARSONS BOULEVARD","PRINCE STREET","PSUEDO PLACE","ROSE AVENUE","SANFORD AVENUE","UNION STREET","UTOPIA PARKWAY","VLEIGH PLACE","WHITESTONE EXPRESSWAY"],
  "jackson heights": ["34 AVENUE","35 AVENUE","37 AVENUE","74 STREET","75 STREET","76 STREET","77 STREET","78 STREET","79 STREET","80 STREET","81 STREET","82 STREET","83 STREET","84 STREET","85 STREET","86 STREET","JUNCTION BOULEVARD","NATIONAL STREET","NORTHERN BOULEVARD","QUEENS BOULEVARD","ROOSEVELT AVENUE"],
  // NYC - Bronx
  "fordham": ["ARTHUR AVENUE","BELMONT AVENUE","BRIGGS AVENUE","CRESTON AVENUE","DAVIDSON AVENUE","FORDHAM ROAD","GRAND AVENUE","GRAND CONCOURSE","JEROME AVENUE","KINGSBRIDGE ROAD","LORING PLACE","MORRIS AVENUE","RYER AVENUE","SOUTHERN BOULEVARD","VALENTINE AVENUE","WEBB AVENUE"],
  "riverdale": ["ARLINGTON AVENUE","BROADWAY","CAMBRIDGE AVENUE","DELAFIELD AVENUE","FIELDSTON ROAD","HENRY HUDSON PARKWAY","INDEPENDENCE AVENUE","JOHNSON AVENUE","KAPPOCK STREET","LIVINGSTON AVENUE","PALISADE AVENUE","RIVERDALE AVENUE","SEMINARY AVENUE","SYCAMORE AVENUE","OXFORD AVENUE","WEST 232 STREET","WEST 236 STREET","WEST 238 STREET","WEST 239 STREET","WEST 240 STREET","WEST 242 STREET","WEST 246 STREET","WEST 247 STREET","WEST 248 STREET","WEST 252 STREET","WEST 254 STREET","WEST 259 STREET","WEST 261 STREET","WALDO AVENUE"],
  // Chicago
  "wicker park": ["AUGUSTA BOULEVARD","BLOOMINGDALE AVENUE","CORTEZ STREET","DIVISION STREET","ELM STREET","HONORE STREET","LEAVITT STREET","LEMOYNE STREET","LINDEN PLACE","MAPLEWOOD AVENUE","MILWAUKEE AVENUE","NORTH AVENUE","PAULINA STREET","PIERCE AVENUE","SCHILLER STREET","THOMAS STREET","WABANSIA AVENUE","WALTON STREET","WICKER PARK AVENUE","WINCHESTER AVENUE","WOLCOTT AVENUE"],
  "logan square": ["ALBANY AVENUE","ARMITAGE AVENUE","CALIFORNIA AVENUE","CENTRAL PARK AVENUE","DIVERSEY AVENUE","DRAKE AVENUE","FULLERTON AVENUE","HAMLIN AVENUE","HARDING AVENUE","KEDZIE AVENUE","KIMBALL AVENUE","LOGAN BOULEVARD","MEDILL AVENUE","MILWAUKEE AVENUE","PALMER SQUARE","SAWYER AVENUE","SPAULDING AVENUE","ST LOUIS AVENUE","WRIGHTWOOD AVENUE"],
  "lincoln park": ["ARMITAGE AVENUE","BELDEN AVENUE","BISSELL STREET","BREWSTER PLACE","BURLING STREET","CLARK STREET","CLEVELAND AVENUE","DAYTON STREET","DEMING PLACE","DICKENS AVENUE","DIVERSEY PARKWAY","FULLERTON AVENUE","HALSTED STREET","KEMPER PLACE","LAKEWOOD AVENUE","LINCOLN AVENUE","MOHAWK STREET","NORTH AVENUE","ORCHARD STREET","SEMINARY AVENUE","SHEFFIELD AVENUE","WAYNE AVENUE","WISCONSIN STREET","WRIGHTWOOD AVENUE"],
  "andersonville": ["BERWYN AVENUE","BALMORAL AVENUE","BOWMANVILLE AVENUE","BRYN MAWR AVENUE","CATALPA AVENUE","CLARK STREET","EDGEWATER AVENUE","FOSTER AVENUE","GLENWOOD AVENUE","GRANVILLE AVENUE","HIGHLAND AVENUE","JEROME STREET","KENMORE AVENUE","LAKEWOOD AVENUE","LUNT AVENUE","MAGNOLIA AVENUE","MORSE AVENUE","PAULINA STREET","RASCHER AVENUE","RIDGE AVENUE","ROSEMONT AVENUE","WAYNE AVENUE","WINTHROP AVENUE"],
  "lakeview": ["ADDISON STREET","BELMONT AVENUE","BROADWAY","BUCKINGHAM PLACE","CLARK STREET","CORNELIA AVENUE","DIVERSEY PARKWAY","EDDY STREET","FLETCHER STREET","FULLERTON AVENUE","GEORGE STREET","GRACE STREET","HALSTED STREET","HAWTHORNE PLACE","LAKEWOOD AVENUE","LINCOLN AVENUE","NEWPORT AVENUE","OAKDALE AVENUE","PATTERSON AVENUE","RACINE AVENUE","ROSCOE STREET","SEMINARY AVENUE","SHEFFIELD AVENUE","SURF STREET","WELLINGTON AVENUE","WOLFRAM STREET"],
  "pilsen": ["16 STREET","17 STREET","18 STREET","19 STREET","21 STREET","ALLPORT STREET","ASHLAND AVENUE","BISHOP STREET","BLUE ISLAND AVENUE","CARPENTER STREET","CERMAK ROAD","CULLERTON STREET","DAMEN AVENUE","HALSTED STREET","LOOMIS STREET","LUMBER STREET","MORGAN STREET","NEWBERRY AVENUE","PEORIA STREET","RACINE AVENUE","SANGAMON STREET","UNION AVENUE","WESTERN AVENUE","WOLCOTT AVENUE","WOOD STREET"],
  // San Francisco
  "mission district": ["16 STREET","17 STREET","18 STREET","19 STREET","20 STREET","21 STREET","22 STREET","23 STREET","24 STREET","25 STREET","26 STREET","BARTLETT STREET","CAPP STREET","CHURCH STREET","DOLORES STREET","GUERRERO STREET","HARRISON STREET","LEXINGTON STREET","LINDA STREET","MISSION STREET","OSAGE ALLEY","POND STREET","SAN CARLOS STREET","SHOTWELL STREET","SOUTH VAN NESS AVENUE","VALENCIA STREET"],
  "haight ashbury": ["ASHBURY STREET","BELVEDERE STREET","BUENA VISTA AVENUE EAST","BUENA VISTA AVENUE WEST","CENTRAL AVENUE","CLAYTON STREET","COLE STREET","DELMAR STREET","DIVISADERO STREET","FREDERICK STREET","GRATTAN STREET","HAIGHT STREET","HEIGHT STREET","LYON STREET","MASONIC AVENUE","PAGE STREET","PIERCE STREET","SHRADER STREET","STANYAN STREET","STATES STREET","WALLER STREET"],
  "castro": ["18 STREET","19 STREET","20 STREET","21 STREET","CASTRO STREET","COLLINGWOOD STREET","CORWIN STREET","DANVERS STREET","DIAMOND STREET","DOUGLASS STREET","EUREKA STREET","FAIR OAKS STREET","FLINT STREET","FORD STREET","HANCOCK STREET","HARTFORD STREET","HENRY STREET","JERSEY STREET","LIBERTY STREET","MARKET STREET","NANDINA STREET","NOE STREET","SANCHEZ STREET","STATES STREET","THRIFT STREET","VALLEY STREET"],
  "noe valley": ["24 STREET","25 STREET","26 STREET","27 STREET","28 STREET","29 STREET","30 STREET","CLIPPER STREET","CHURCH STREET","DIAMOND STREET","DOLORES STREET","DOUGLASS STREET","ELIZABETH STREET","EUREKA STREET","FAIR OAKS STREET","HOFFMAN AVENUE","JERSEY STREET","LIBERTY STREET","NOE STREET","SANCHEZ STREET","VALLEY STREET","VICKSBURG STREET","WHITNEY STREET"],
  "soma": ["1 STREET","2 STREET","3 STREET","4 STREET","5 STREET","6 STREET","7 STREET","8 STREET","9 STREET","10 STREET","BRANNAN STREET","BRYANT STREET","CHANNEL STREET","CLEMENTINA STREET","FOLSOM STREET","FREELON STREET","HARRISON STREET","HOWARD STREET","KING STREET","MINNA STREET","MISSION STREET","NATOMA STREET","RAUSCH STREET","RINCON STREET","SHIPLEY STREET","STILLMAN STREET","TEHAMA STREET","TOWNSEND STREET","WELSH STREET"],
  // Los Angeles
  "silver lake": ["AARON STREET","ADELBERT AVENUE","ANGUS STREET","BERKELEY AVENUE","BRIER AVENUE","CLINTON STREET","COVE AVENUE","DUANE STREET","EAST SILVER LAKE DRIVE","EFFIE STREET","ELKWOOD STREET","FARGO STREET","FOUNTAIN AVENUE","GLENDALE BOULEVARD","GRIFFITH PARK BOULEVARD","HAMLIN STREET","HYPERION AVENUE","IVAN HILL TERRACE","KENILWORTH AVENUE","LEMOYNE STREET","LESLER PLACE","MALTMAN AVENUE","MARATHON STREET","MICHELTORENA STREET","MORENO DRIVE","REDCLIFF STREET","ROWENA AVENUE","SANBORN AVENUE","SILVER LAKE BOULEVARD","SUNSET BOULEVARD","TESLA AVENUE","TREMAINE AVENUE","WAVERLY DRIVE"],
  "echo park": ["AARON STREET","ALLESANDRO STREET","BAXTER STREET","BELLEVUE AVENUE","BERKELEY AVENUE","CLINTON STREET","COURT STREET","DELTA STREET","ECHO PARK AVENUE","ELSINORE STREET","FILIPINOTOWN","GLENDALE BOULEVARD","KENT STREET","LAKE SHORE AVENUE","LAVETA TERRACE","LEMOYNE STREET","LOGAN STREET","LUCRETIA AVENUE","MORTON AVENUE","PARK DRIVE","PARKMAN AVENUE","PORTIA STREET","ROSEMONT AVENUE","SCOTT AVENUE","SUNSET BOULEVARD","TEMPLE STREET","VESTAL AVENUE","WATERLOO STREET"],
  "west hollywood": ["ALTA LOMA ROAD","BEST AVENUE","CYNTHIA STREET","DOHENY DRIVE","FOUNTAIN AVENUE","GARDNER STREET","GENESEE AVENUE","HAVENHURST DRIVE","HILLDALE AVENUE","HOLLOWAY DRIVE","LA JOLLA AVENUE","LARRABEE STREET","LAUREL AVENUE","LEICESTER PLACE","NORMA PLACE","NORTH VISTA STREET","PALM AVENUE","ROBERTSON BOULEVARD","SAN VICENTE BOULEVARD","SANTA MONICA BOULEVARD","SHERBOURNE DRIVE","SUNSET BOULEVARD","SWEETZER AVENUE","VISTA DEL MAR","WETHERLY DRIVE"],
  "koreatown": ["8 STREET","9 STREET","10 STREET","11 STREET","12 STREET","ARDMORE AVENUE","BERENDO STREET","CATALINA STREET","COMMONWEALTH AVENUE","GATES STREET","HARVARD BOULEVARD","IROLO STREET","KENMORE AVENUE","KINGSLEY DRIVE","MANHATTAN PLACE","MARIPOSA AVENUE","NORMANDIE AVENUE","OXFORD AVENUE","SERRANO AVENUE","SHATTO PLACE","VERMONT AVENUE","WESTERN AVENUE","WILSHIRE BOULEVARD"],
  // Boston
  "south end": ["APPLETON STREET","BERKELEY STREET","BLACKWOOD STREET","BRADDOCK PARK","CAMDEN STREET","CHANDLER STREET","CLARENDON STREET","COLUMBUS AVENUE","DARTMOUTH STREET","DEDHAM STREET","DWIGHT STREET","EAST BROOKLINE STREET","EAST CANTON STREET","EAST CONCORD STREET","EAST NEWTON STREET","EAST SPRINGFIELD STREET","EDGERLY ROAD","GRAY STREET","MASSACHUSETTS AVENUE","MILFORD STREET","MONTGOMERY STREET","NORTHAMPTON STREET","PEMBROKE STREET","RUTLAND SQUARE","RUTLAND STREET","SHAWMUT AVENUE","TREMONT STREET","UNION PARK STREET","WALTHAM STREET","WARREN AVENUE","WEST BROOKLINE STREET","WEST CANTON STREET","WEST CONCORD STREET","WEST DEDHAM STREET","WEST NEWTON STREET","WORCESTER SQUARE"],
  "back bay": ["ARLINGTON STREET","BEACON STREET","BERKELEY STREET","BOYLSTON STREET","CLARENDON STREET","COMMONWEALTH AVENUE","DARTMOUTH STREET","EXETER STREET","FAIRFIELD STREET","GLOUCESTER STREET","HEREFORD STREET","HUNTINGTON AVENUE","MASSACHUSETTS AVENUE","MARLBOROUGH STREET","NEWBURY STREET","RING ROAD","STORROW DRIVE"],
  "jamaica plain": ["CENTRE STREET","CHESTNUT AVENUE","CHILD STREET","CIRCUIT STREET","CITY VIEW STREET","CONGRESS STREET","ELEANOR STREET","ESMOND STREET","FOREST HILLS STREET","GREEN STREET","GREENWAY","GREENWICH PARK","HALL STREET","HEATH STREET","HIGH STREET","JAMAICA WAY","LAMARTINE STREET","LAWN STREET","LONDON STREET","LOUISBURG SQUARE","MCBRIDE STREET","MONTEBELLO ROAD","MOSS HILL ROAD","PARLEY VALE","PERKINS STREET","POND STREET","PRINCE STREET","SOUTH HUNTINGTON AVENUE","SOUTH STREET","SUMNER STREET","SUNNYSIDE STREET","WASHINGTON STREET"],
  "beacon hill": ["ACORN STREET","ANDERSON STREET","BOWDOIN STREET","CAMBRIDGE STREET","CEDAR LANE WAY","CHESTNUT STREET","DERNE STREET","HANCOCK STREET","JOY STREET","LOUISBURG SQUARE","MARGARET STREET","MYRTLE STREET","MT VERNON STREET","OLIVE STREET","PHILLIPS STREET","PINCKNEY STREET","REVERE STREET","RIVER STREET","SPRUCE STREET","TEMPLE STREET","WALNUT STREET","WEST CEDAR STREET"],
  // Philadelphia
  "fishtown": ["ALLEN STREET","ARABELLA STREET","BERKS STREET","COLUMBIA AVENUE","CORK STREET","CREASE STREET","EAST BERKS STREET","EAST GIRARD AVENUE","EAST MASTER STREET","EAST MONTGOMERY AVENUE","EAST SUSQUEHANNA AVENUE","HAGERT STREET","HEMP STREET","HOMER STREET","MARLBOROUGH STREET","MASTER STREET","MEMPHIS STREET","MOYER STREET","NORRIS STREET","RICHMOND STREET","SHACKAMAXON STREET","THOMPSON STREET","VIENNA STREET","WILDEY STREET"],
  "northern liberties": ["AMERICAN STREET","BROWN STREET","BUTTONWOOD STREET","CALLOWHILL STREET","CANAL STREET","FAIRMOUNT AVENUE","GEORGE STREET","GIRARD AVENUE","GREEN STREET","HANCOCK STREET","LAUREL STREET","MELON STREET","NEW MARKET STREET","NOBLE STREET","NORTH SECOND STREET","NORTH THIRD STREET","NORTH FOURTH STREET","NORTH FIFTH STREET","NORTH SIXTH STREET","POPLAR STREET","SPRING GARDEN STREET","SUGAR STREET","THOMPSON STREET","WILDEY STREET"],
  "rittenhouse": ["16 STREET","17 STREET","18 STREET","19 STREET","20 STREET","21 STREET","CHANCELLOR STREET","CHESTNUT STREET","DELANCEY PLACE","LOCUST STREET","MANNING STREET","MORAVIAN STREET","NAUDAIN STREET","PINE STREET","RITTENHOUSE SQUARE","SANSOM STREET","SPRUCE STREET","WALNUT STREET"],
  // Washington DC
  "adams morgan": ["18 STREET NW","BELMONT STREET NW","BILTMORE STREET NW","CALVERT STREET NW","COLUMBIA ROAD NW","EUCLID STREET NW","HARVARD STREET NW","KALORAMA ROAD NW","LANIER PLACE NW","ONTARIO ROAD NW","ONTARIO PLACE NW","PARK ROAD NW","PERRY STREET NW","QUINCY PLACE NW","RIGGS PLACE NW","SWANN STREET NW","Vernon STREET NW","WILLARD STREET NW"],
  "dupont circle": ["19 STREET NW","20 STREET NW","21 STREET NW","22 STREET NW","23 STREET NW","CHURCH STREET NW","CORCORAN STREET NW","CONNECTICUT AVENUE NW","FLORIDA AVENUE NW","MASSACHUSETTS AVENUE NW","NEW HAMPSHIRE AVENUE NW","P STREET NW","Q STREET NW","R STREET NW","S STREET NW","SUNDERLAND PLACE NW","SWANN STREET NW","T STREET NW"],
  "capitol hill": ["1 STREET NE","1 STREET SE","2 STREET NE","2 STREET SE","3 STREET NE","3 STREET SE","4 STREET NE","4 STREET SE","A STREET NE","A STREET SE","B STREET NE","B STREET SE","C STREET NE","C STREET SE","D STREET NE","D STREET SE","E STREET NE","E STREET SE","EAST CAPITOL STREET","F STREET NE","CONSTITUTION AVENUE NE","INDEPENDENCE AVENUE SE","MARYLAND AVENUE NE","MASSACHUSETTS AVENUE NE","NORTH CAROLINA AVENUE SE","PENNSYLVANIA AVENUE SE"],
  // Seattle
  "capitol hill": ["10 AVENUE","11 AVENUE","12 AVENUE","13 AVENUE","14 AVENUE","15 AVENUE","BELLEVUE AVENUE","BOYLSTON AVENUE","BROADWAY","DENNY WAY","E DENNY WAY","E JOHN STREET","E MADISON STREET","E OLIVE WAY","E PIKE STREET","E PINE STREET","E ROY STREET","E SPRING STREET","E UNION STREET","EASTLAKE AVENUE","HARVARD AVENUE","LAKEVIEW BOULEVARD","MELROSE AVENUE","REPUBLICAN STREET","SUMMIT AVENUE","TERRY AVENUE","THOMAS STREET","YALE AVENUE"],
  "fremont": ["1 AVENUE N","2 AVENUE N","3 AVENUE N","4 AVENUE N","34 STREET","35 STREET","36 STREET","37 STREET","38 STREET","39 STREET","40 STREET","41 STREET","AURORA AVENUE N","BURKE AVENUE N","DAYTON AVENUE N","DEXTER AVENUE N","EVANSTON AVENUE N","FREMONT AVENUE N","FREMONT PLACE N","GREENWOOD AVENUE N","INTERLAKE AVENUE N","LINDEN AVENUE N","MERIDIAN AVENUE N","N 34 STREET","N 36 STREET","PALATINE AVENUE N","PHINNEY AVENUE N","STONE WAY N","WOODLAND PARK AVENUE N"],
  "ballard": ["14 AVENUE NW","15 AVENUE NW","17 AVENUE NW","20 AVENUE NW","22 AVENUE NW","24 AVENUE NW","28 AVENUE NW","32 AVENUE NW","56 STREET NW","57 STREET NW","58 STREET NW","59 STREET NW","60 STREET NW","65 STREET NW","MARKET STREET","NW 56 STREET","NW 57 STREET","NW 58 STREET","NW 65 STREET","SHILSHOLE AVENUE NW","SLOOP STREET","STONEWAY N"],
};

function lookupNeighborhoodStreets(name) {
  const key = name.toLowerCase().trim()
    .replace(/,?\s*(brooklyn|manhattan|queens|bronx|staten island|chicago|los angeles|la|san francisco|sf|boston|philadelphia|philly|washington dc|dc|seattle|new york|nyc|ny)\s*$/i, "")
    .trim();
  return NEIGHBORHOOD_STREETS[key] || null;
}

// ─── GET STREETS FOR A NEIGHBORHOOD ──────────────────────────────────────────
async function getNeighborhoodStreets(neighborhoodName, lat, lng) {
  // First check hardcoded catalog — instant and reliable
  const hardcoded = lookupNeighborhoodStreets(neighborhoodName);
  if (hardcoded) {
    console.log(`Catalog hit for "${neighborhoodName}": ${hardcoded.length} streets`);
    return hardcoded;
  }

  // Fallback: OSM radius query for neighborhoods not in catalog
  console.log(`No catalog entry for "${neighborhoodName}", using OSM radius`);
  try {
    const overpassQuery = `[out:json][timeout:15];way(around:700,${lat},${lng})["highway"~"^(residential|secondary|tertiary|primary|unclassified|living_street|pedestrian)$"]["name"];out tags;`;
    const r = await fetch(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(overpassQuery)}`, {
      headers: { "User-Agent": "MoveMyCar/1.0" }
    });
    if (!r.ok) return [];
    const data = await r.json();
    return [...new Set((data.elements || []).map(w => w.tags?.name?.toUpperCase()).filter(Boolean))].sort();
  } catch(e) {
    console.error("OSM fallback error:", e.message);
    return [];
  }
}

// ─── SMART GEOCODE ────────────────────────────────────────────────────────────
app.get("/api/geocode", async (req, res) => {
  const { q, userLat, userLng } = req.query;
  if (!q) return res.status(400).json({ error: "q required" });

  const GOOGLE_KEY = process.env.GOOGLE_MAPS_KEY;

  // ── STEP 1: If it looks like a full address, go straight to Google ────────
  const looksLikeAddress = /^\d+\s+\w/.test(q.trim());
  if (looksLikeAddress && GOOGLE_KEY) {
    try {
      const stripped = q.replace(/\s*(apt|apartment|unit|suite|ste|fl|floor|#)\s*[\w-]+/gi, "").replace(/\(.*?\)/g, "").trim();
      const gUrl = `https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(stripped)}&key=${GOOGLE_KEY}&region=us&components=country:US`;
      const gr = await fetch(gUrl);
      if (gr.ok) {
        const gd = await gr.json();
        if (gd.status === "OK" && gd.results?.length > 0) {
          const result = gd.results[0];
          const loc = result.geometry.location;
          const lat = loc.lat, lng = loc.lng;
          const comps = result.address_components || [];
          const get = (type) => comps.find(c => c.types.includes(type))?.long_name || "";
          const street = (get("route") || q).toUpperCase();
          const neighborhood = get("neighborhood") || get("sublocality_level_2") || "";
          const borough = get("sublocality_level_1") || get("sublocality") || "";
          const city = get("locality") || "";
          const label = result.formatted_address?.split(",").slice(0,2).join(",") || q;

          // Get nearby streets sorted by proximity
          let nearbyStreets = [street];
          try {
            const raw = await askClaude(`Urban geography expert. Coordinates lat=${lat}, lng=${lng} in ${neighborhood || borough || city}. List 12 nearest streets sorted closest to farthest. Primary street: "${street}". Return ONLY a JSON array of street names in ALL CAPS.`, 800);
            const match = raw.match(/\[[\s\S]*\]/);
            if (match) { const parsed = JSON.parse(match[0]); if (Array.isArray(parsed) && parsed.length > 0) nearbyStreets = parsed; }
          } catch(e) {}

          return res.json({ type:"location", isGPS:true, isEstablishment:false, isPark:false, isZip:false, street, borough, neighborhood, city, label, originalQuery:q, lat, lng, nearbyStreets });
        }
      }
    } catch(e) { console.error("Google address geocode error:", e.message); }
  }

  let raw = "";
  try {
    raw = await askClaude(`You are a US urban geography and parking expert covering all major cities. A driver typed: "${q}"

First detect the CITY this refers to. Supported cities: New York City, Los Angeles, Chicago, San Francisco, Boston, Philadelphia, Washington DC, Seattle, Miami, Atlanta, Toronto, Denver, Portland OR, Nashville, Austin, Minneapolis.
If no city is clear from the query, default to New York City.

Then classify the query using the same types as before.

LOCAL SLANG AND NICKNAMES BY CITY:
NYC: "the city"=Manhattan | "BK"=Brooklyn | "the bronx"=Bronx | "SI"=Staten Island | "LIC"=Long Island City | "UWS"=Upper West Side | "UES"=Upper East Side | "HK" or "Hell's Kitchen"=Clinton | "Noho","Soho","Tribeca","Dumbo","Nolita"=neighborhoods | "the village"=Greenwich Village | "alphabet city"=East Village | "the slope"=Park Slope | "the heights"=Washington Heights or Brooklyn Heights | "Ditmas"=Ditmas Park | "Prospect-Lefferts"=PLG
LA: "WeHo"=West Hollywood | "SaMo"=Santa Monica | "DTLA"=Downtown LA | "the valley"=San Fernando Valley | "Los Feliz"=Los Feliz | "Sil Lake"=Silver Lake | "echo"=Echo Park | "Bev Hills"=Beverly Hills | "Palms"=Palms | "Mar Vista"=Mar Vista | "Culver"=Culver City | "K-town"=Koreatown | "MacArthur Park"=Westlake | "the eastside"=East LA/Boyle Heights
Chicago: "the loop"=Loop | "Wicker"=Wicker Park | "Boystown"=Lakeview East | "the mag mile"=Magnificent Mile | "Pilsen"=Pilsen | "Little Village"=South Lawndale | "Bridgeport"=Bridgeport | "Lincoln Square"=Lincoln Square | "RoNo"=Rogers Park | "Andersonville"=Andersonville | "Uptown"=Uptown | "Humboldt"=Humboldt Park | "Logan"=Logan Square | "Ukrainian Village"=Ukrainian Village | "Noble Square"=Noble Square
SF: "the mish"=Mission District | "the haight"=Haight-Ashbury | "SOMA"=South of Market | "the TL"=Tenderloin | "Noe"=Noe Valley | "the castro"=Castro | "the avenues"=Sunset/Richmond | "the sunset"=Outer Sunset | "inner sunset"=Inner Sunset | "the richmond"=Richmond District | "dogpatch"=Dogpatch | "potrero"=Potrero Hill | "bernal"=Bernal Heights | "glen park"=Glen Park | "excelsior"=Excelsior | "visitacion"=Visitacion Valley | "bayview"=Bayview | "hunters point"=Hunters Point
Boston: "JP"=Jamaica Plain | "Dot"=Dorchester | "Southie"=South Boston | "Eastie"=East Boston | "the north end"=North End | "Allston/Brighton"=Allston | "the fenway"=Fenway | "the back bay"=Back Bay | "beacon hill"=Beacon Hill | "the south end"=South End | "Rozzie"=Roslindale | "West Rox"=West Roxbury | "Hyde Park"=Hyde Park | "Charlestown"=Charlestown | "Camberville"=Cambridge/Somerville
Philadelphia: "Fishtown"=Fishtown | "NoLibs"=Northern Liberties | "Fairmount"=Fairmount | "the Italian market"=South Philly | "Rittenhouse"=Rittenhouse Square | "Old City"=Old City | "Manayunk"=Manayunk | "Kensington"=Kensington | "West Philly"=West Philadelphia | "Mt Airy"=Mount Airy | "Chestnut Hill"=Chestnut Hill | "East Falls"=East Falls | "Roxborough"=Roxborough
DC: "Adams Morgan"=Adams Morgan | "U Street"=U Street Corridor | "H Street"=H Street NE | "the Hill"=Capitol Hill | "Navy Yard"=Navy Yard | "Georgetown"=Georgetown | "Dupont"=Dupont Circle | "Woodley"=Woodley Park | "Columbia Heights"=Columbia Heights | "Petworth"=Petworth | "Shaw"=Shaw | "Logan"=Logan Circle | "NoMa"=North of Massachusetts Ave | "Brookland"=Brookland
Seattle: "Cap Hill"=Capitol Hill | "Fremont"=Fremont | "Ballard"=Ballard | "the CD"=Central District | "SLU"=South Lake Union | "Beacon"=Beacon Hill | "Columbia City"=Columbia City | "Georgetown"=Georgetown | "SODO"=South of Downtown | "Belltown"=Belltown | "Queen Anne"=Queen Anne | "Magnolia"=Magnolia | "Greenlake"=Green Lake | "Wallingford"=Wallingford | "U District"=University District | "Ravenna"=Ravenna

KEY COORDS BY CITY:
NYC: times sq=40.7580,-73.9855 | central park=40.7851,-73.9683 | brooklyn heights=40.6960,-73.9951 | williamsburg=40.7081,-73.9571 | astoria=40.7721,-73.9302 | greenpoint=40.7282,-73.9542 | park slope=40.6681,-73.9800 | lic=40.7447,-73.9485 | harlem=40.8116,-73.9465 | flushing=40.7675,-73.8330 | washington heights=40.8448,-73.9387
LA: dtla=34.0522,-118.2437 | santa monica=34.0195,-118.4912 | west hollywood=34.0900,-118.3617 | silver lake=34.0870,-118.2695 | echo park=34.0780,-118.2606 | los feliz=34.1064,-118.2931 | koreatown=34.0586,-118.3005 | culver city=34.0211,-118.3965 | venice=33.9850,-118.4695 | pasadena=34.1478,-118.1445 | long beach=33.7701,-118.1937
Chicago: loop=41.8827,-87.6233 | wicker park=41.9088,-87.6797 | lincoln park=41.9214,-87.6513 | lakeview=41.9400,-87.6553 | logan square=41.9217,-87.7079 | pilsen=41.8543,-87.6576 | hyde park=41.7943,-87.5907 | andersonville=41.9812,-87.6680 | humboldt park=41.9006,-87.7226 | boystown=41.9436,-87.6490
SF: mission=37.7599,-122.4148 | haight=37.7692,-122.4481 | soma=37.7785,-122.3948 | castro=37.7609,-122.4350 | noe valley=37.7502,-122.4337 | richmond=37.7780,-122.4830 | sunset=37.7525,-122.4875 | bernal heights=37.7390,-122.4153 | dogpatch=37.7596,-122.3902 | potrero hill=37.7590,-122.4014
Boston: back bay=42.3503,-71.0810 | south end=42.3398,-71.0746 | beacon hill=42.3588,-71.0707 | cambridge=42.3736,-71.1097 | jamaica plain=42.3100,-71.1128 | dorchester=42.3014,-71.0641 | south boston=42.3388,-71.0447 | charlestown=42.3782,-71.0602 | allston=42.3540,-71.1323 | fenway=42.3467,-71.0972
Philadelphia: center city=39.9526,-75.1652 | fishtown=39.9748,-75.1338 | northern liberties=39.9637,-75.1416 | south philly=39.9186,-75.1687 | west philly=39.9484,-75.2182 | manayunk=40.0278,-75.2266 | germantown=40.0359,-75.1724 | fairmount=39.9685,-75.1768 | rittenhouse=39.9496,-75.1727
DC: georgetown=38.9076,-77.0723 | dupont=38.9096,-77.0434 | adams morgan=38.9211,-77.0419 | capitol hill=38.8897,-77.0038 | u street=38.9177,-77.0319 | columbia heights=38.9284,-77.0317 | navy yard=38.8762,-77.0053 | shaw=38.9122,-77.0231 | brookland=38.9344,-76.9941 | petworth=38.9394,-77.0269
Seattle: capitol hill=47.6253,-122.3222 | fremont=47.6510,-122.3500 | ballard=47.6685,-122.3829 | belltown=47.6148,-122.3468 | queen anne=47.6373,-122.3565 | slu=47.6261,-122.3353 | central district=47.6062,-122.3014 | beacon hill=47.5693,-122.3070 | georgetown=47.5485,-122.3237 | u district=47.6614,-122.3152
Miami: brickell=25.7617,-80.1918 | wynwood=25.8008,-80.1993 | little havana=25.7667,-80.2270 | coconut grove=25.7253,-80.2385 | miami beach=25.7907,-80.1300 | south beach=25.7825,-80.1341 | midtown=25.8120,-80.1934 | design district=25.8153,-80.1960 | downtown=25.7742,-80.1937 | edgewater=25.7942,-80.1874
Atlanta: midtown=33.7842,-84.3830 | buckhead=33.8484,-84.3788 | little five points=33.7649,-84.3507 | inman park=33.7524,-84.3535 | old fourth ward=33.7573,-84.3630 | virginia highland=33.7774,-84.3491 | east atlanta=33.7352,-84.3396 | west end=33.7344,-84.4130 | cabbagetown=33.7480,-84.3621 | grant park=33.7348,-84.3731
Toronto: kensington market=43.6547,-79.4009 | queen west=43.6454,-79.4157 | distillery district=43.6503,-79.3592 | annex=43.6687,-79.4057 | yorkville=43.6709,-79.3924 | little italy=43.6554,-79.4210 | leslieville=43.6617,-79.3341 | roncesvalles=43.6473,-79.4486 | ossington=43.6522,-79.4244 | parkdale=43.6378,-79.4445
Denver: lodo=39.7537,-104.9999 | rino=39.7687,-104.9766 | capitol hill=39.7296,-104.9805 | highland=39.7638,-105.0121 | wash park=39.6969,-104.9660 | cherry creek=39.7153,-104.9521 | five points=39.7534,-104.9741 | baker=39.7136,-104.9861 | curtis park=39.7579,-104.9700 | whittier=39.7500,-104.9614
Portland: pearl district=45.5266,-122.6836 | alberta arts=45.5593,-122.6375 | hawthorne=45.5116,-122.6385 | mississippi ave=45.5546,-122.6769 | division=45.5033,-122.6348 | nob hill=45.5280,-122.6957 | inner southeast=45.5118,-122.6490 | woodstock=45.4844,-122.6262 | sellwood=45.4686,-122.6543 | st johns=45.5927,-122.7519
Nashville: east nashville=36.1741,-86.7580 | 12 south=36.1201,-86.7970 | germantown=36.1784,-86.7878 | gulch=36.1502,-86.7937 | sylvan park=36.1536,-86.8327 | hillsboro village=36.1354,-86.8038 | belmont=36.1301,-86.7925 | five points=36.1748,-86.7517 | nations=36.1594,-86.8582 | buena vista=36.1653,-86.8046
Austin: south congress=30.2432,-97.7503 | east austin=30.2589,-97.7202 | north loop=30.3184,-97.7200 | mueller=30.2970,-97.7032 | domain=30.4021,-97.7237 | rainey street=30.2587,-97.7389 | west campus=30.2901,-97.7463 | travis heights=30.2378,-97.7415 | clarksville=30.2795,-97.7614 | cherrywood=30.2784,-97.7220
Minneapolis: uptown=44.9488,-93.2986 | northeast=44.9940,-93.2561 | north loop=44.9874,-93.2755 | dinkytown=44.9812,-93.2350 | seward=44.9499,-93.2278 | longfellow=44.9287,-93.2213 | south minneapolis=44.9138,-93.2707 | st anthony=44.9830,-93.2474 | powderhorn=44.9265,-93.2557 | linden hills=44.9110,-93.3251

Return the same JSON format as before but include a "city" field in every response.
For NEIGHBORHOOD type include the city in the label e.g. "Wicker Park, Chicago".
For LOCATION type include city and state e.g. "Silver Lake, Los Angeles".

AMBIGUOUS EXAMPLES (cross-city):
- "lincoln park" → ambiguous: neighborhood Chicago + park NYC
- "georgetown" → ambiguous: neighborhood DC + neighborhood Seattle
- "mission" → ambiguous: neighborhood SF (Mission District) + could be other cities

NEIGHBORHOOD EXAMPLES — ALWAYS return as neighborhood type with ALL streets listed in neighborhoodStreets:
- "west village" → neighborhood Manhattan: BANK ST, BARROW ST, BEDFORD ST, BETHUNE ST, CHARLES ST, CHRISTOPHER ST, CLARKSON ST, COMMERCE ST, CORNELIA ST, GROVE ST, HORATIO ST, HUDSON ST, JANE ST, LEROY ST, MORTON ST, PERRY ST, TENTH AVENUE, WASHINGTON ST, WEST 10 STREET, WEST 11 STREET, WEST 12 STREET, WEST 4 STREET, WEST STREET
- "east village" → neighborhood Manhattan with all streets
- "brooklyn heights" → neighborhood Brooklyn with all streets
- "park slope" → neighborhood Brooklyn with all streets
- "upper west side" → neighborhood Manhattan with all streets
- "hell's kitchen" → neighborhood Manhattan with all streets
- "greenwich village" → neighborhood Manhattan with all streets
- "soho" → neighborhood Manhattan with all streets
- "tribeca" → neighborhood Manhattan with all streets
- "dumbo" → neighborhood Brooklyn with all streets
- "williamsburg" → neighborhood Brooklyn with all streets
- "bushwick" → neighborhood Brooklyn with all streets
- "wicker park" → neighborhood Chicago with all streets
- "logan square" → neighborhood Chicago with all streets
- "silver lake" → neighborhood LA with all streets
- "echo park" → neighborhood LA with all streets
- "mission district" → neighborhood SF with all streets
- "haight ashbury" → neighborhood SF with all streets
- "capitol hill" → neighborhood Seattle with all streets
- "adams morgan" → neighborhood DC with all streets
- "south end" → neighborhood Boston with all streets
- "fishtown" → neighborhood Philadelphia with all streets
- "northern liberties" → neighborhood Philadelphia with all streets

LOCATION EXAMPLES (landmarks/plazas/squares — return as location type with coords):
- "court square" → location in LIC Queens, lat=40.7472, lng=-73.9454
- "times square" → location Manhattan, lat=40.7580, lng=-73.9855
- "union square" → location Manhattan OR SF depending on context
- "the met" → establishment (Metropolitan Museum) on 5th Ave Manhattan
- "wrigley field" → establishment in Chicago
- "grand army plaza" → location Brooklyn, lat=40.6742, lng=-73.9700

Return ONLY the JSON, no markdown.`, 3000);

    const loc = JSON.parse(raw.replace(/```json|```/g,"").trim());

    if (loc.type === "ambiguous") return res.json({ ...loc, originalQuery: q });

    // Neighborhood — get real streets from OpenStreetMap
    if (loc.type === "neighborhood" || loc.isNeighborhood) {
      const streets = await getNeighborhoodStreets(q, loc.lat, loc.lng);
      console.log(`Neighborhood "${q}": ${streets.length} streets from OSM`);
      return res.json({ ...loc, isNeighborhood: true, isZip: false, isPark: false, isEstablishment: false, zipStreets: streets, originalQuery: q });
    }

    // If Claude returned a location but it's a well-known neighborhood name, treat as neighborhood
    if (loc.type === "location" && loc.lat) {
      const neighborhoodKeywords = /village|heights|slope|park|hill|garden|square|place|town|side|point|field|wood|grove|bridge|haven|beach|bay|harbor|quarter|district|corridor|triangle|oval|circle|loop|row|mish|haight|dumbo|soho|tribeca|noho|nolita|bushwick|williamsburg|astoria|flushing|sunnyside/i;
      const isLikelyNeighborhood = neighborhoodKeywords.test(q) && !q.match(/^\d+/) && !q.includes("&") && q.split(" ").length <= 4;
      if (isLikelyNeighborhood) {
        console.log(`Treating "${q}" as neighborhood, fetching OSM streets`);
        const streets = await getNeighborhoodStreets(q, loc.lat, loc.lng);
        if (streets.length > 0) {
          return res.json({ ...loc, isNeighborhood: true, isZip: false, isPark: false, isEstablishment: false, zipStreets: streets, originalQuery: q });
        }
      }
    }

    if (loc.isEstablishment && loc.establishments?.length > 0 && userLat && userLng) {
      const uLat = parseFloat(userLat), uLng = parseFloat(userLng);
      loc.establishments.sort((a,b) => haversineKm(uLat,uLng,a.lat,a.lng) - haversineKm(uLat,uLng,b.lat,b.lng));
    }

    // For single locations (landmarks, plazas, intersections), return nearby streets
    if (!loc.isEstablishment && !loc.isPark && !loc.isZip && loc.lat && loc.lng) {
      try {
        const raw = await askClaude(`You are an urban geography expert. Given coordinates lat=${loc.lat}, lng=${loc.lng} near "${q}" (${loc.neighborhood || loc.borough || loc.city || ""}), list the 12 nearest streets sorted closest to farthest. The primary street is "${loc.street}".

Return ONLY a JSON array of street names in ALL CAPS. Include cross streets and parallel streets within a 6-block radius.
Return ONLY the array.`, 1000);
        const match = raw.match(/\[[\s\S]*\]/);
        if (match) {
          const parsed = JSON.parse(match[0]);
          if (Array.isArray(parsed) && parsed.length > 0) {
            return res.json({ ...loc, isGPS: true, nearbyStreets: parsed, originalQuery: q });
          }
        }
      } catch(e) { console.error("Nearby streets for location error:", e.message); }
    }

    if (loc.isEstablishment || loc.isPark || loc.isZip || loc.lat) {
      return res.json({ ...loc, originalQuery: q });
    }
  } catch (e) { console.error("Claude geocode error:", e.message); }

  // Google Geocoding API — handles landmarks, abbreviations, full addresses, neighborhoods
  try {
    let stripped = q
      .replace(/\s*(apt|apartment|unit|suite|ste|fl|floor|#)\s*[\w-]+/gi, "")
      .replace(/\(.*?\)/g, "")
      .trim();

    const GOOGLE_KEY = process.env.GOOGLE_MAPS_KEY;
    const gUrl = `https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(stripped)}&key=${GOOGLE_KEY}&region=us&components=country:US`;
    const gr = await fetch(gUrl);
    if (gr.ok) {
      const gd = await gr.json();
      if (gd.status === "OK" && gd.results?.length > 0) {
        const result = gd.results[0];
        const loc = result.geometry.location;
        const lat = loc.lat, lng = loc.lng;
        const comps = result.address_components || [];
        const get = (type) => comps.find(c => c.types.includes(type))?.long_name || "";
        const street = (get("route") || q).toUpperCase();
        const streetNum = get("street_number");
        const neighborhood = get("neighborhood") || get("sublocality_level_2") || "";
        const borough = get("sublocality_level_1") || get("sublocality") || "";
        const city = get("locality") || "";
        const label = result.formatted_address?.split(",").slice(0,2).join(",") || q;

        // If it's a street address, return surrounding streets sorted by proximity
        const isAddress = /^\d+\s+\w/.test(stripped.trim()) || !!streetNum;
        if (isAddress) {
          let nearbyStreets = [street];
          try {
            const raw = await askClaude(`You are an urban geography expert. Given coordinates lat=${lat}, lng=${lng} in ${neighborhood || borough || city}, list the 12 nearest streets sorted closest to farthest. The primary street is "${street}".

Return ONLY a JSON array of street names in ALL CAPS. Include cross streets and parallel streets within a 6-block radius.
Return ONLY the array.`, 1000);
            const match = raw.match(/\[[\s\S]*\]/);
            if (match) {
              const parsed = JSON.parse(match[0]);
              if (Array.isArray(parsed) && parsed.length > 0) nearbyStreets = parsed;
            }
          } catch(e) { console.error("Nearby streets error:", e.message); }

          return res.json({
            type: "location", isGPS: true, isEstablishment: false, isPark: false, isZip: false,
            street, borough, neighborhood, city, label, originalQuery: q, lat, lng, nearbyStreets,
          });
        }

        return res.json({ type:"location", isEstablishment:false, isPark:false, isZip:false, street, borough, neighborhood, city, label, originalQuery:q, lat, lng });
      }
    }
  } catch (e) { console.error("Google geocode error:", e.message); }

  res.status(404).json({ error: `Couldn't find "${q}". Try a street name, zip code, or neighborhood in NYC, LA, Chicago, SF, Boston, Philadelphia, DC, Seattle, Miami, Atlanta, Toronto, Denver, Portland, Nashville, Austin, or Minneapolis.` });
});

// Reverse geocode — uses Google for accuracy, returns nearby streets sorted by distance
app.get("/api/reverse-geocode", async (req, res) => {
  const { lat, lng } = req.query;
  if (!lat || !lng) return res.status(400).json({ error: "lat and lng required" });

  let primaryStreet = "", borough = "", neighborhood = "", label = "", city = "";

  try {
    const GOOGLE_KEY = process.env.GOOGLE_MAPS_KEY;
    const url = `https://maps.googleapis.com/maps/api/geocode/json?latlng=${lat},${lng}&key=${GOOGLE_KEY}`;
    const r = await fetch(url);
    if (r.ok) {
      const data = await r.json();
      if (data.status === "OK" && data.results?.length > 0) {
        const result = data.results[0];
        const comps = result.address_components || [];
        const get = (type) => comps.find(c => c.types.includes(type))?.long_name || "";
        primaryStreet = get("route").toUpperCase();
        borough       = get("sublocality_level_1") || get("sublocality") || "";
        neighborhood  = get("neighborhood") || get("sublocality_level_2") || "";
        city          = get("locality") || "";
        label         = result.formatted_address?.split(",").slice(0,2).join(",") || "";
      }
    }
  } catch (e) { console.error("Google reverse geocode error:", e.message); }

  if (!primaryStreet) return res.status(502).json({ error: "Could not identify your street" });

  // Get nearby streets sorted by distance using Nominatim search in bounding box
  let nearbyStreets = [];
  try {
    const raw = await askClaude(`You are an urban geography expert. Given coordinates lat=${lat}, lng=${lng} (${neighborhood}, ${borough}), list the 12 nearest streets sorted from closest to farthest. The primary street is "${primaryStreet}".

Return ONLY a JSON array of street names in ALL CAPS. Include cross streets and parallel streets within a 6-block radius.
Return ONLY the JSON array.`, 1000);
    const match = raw.match(/\[[\s\S]*\]/);
    if (match) {
      const parsed = JSON.parse(match[0]);
      if (Array.isArray(parsed) && parsed.length > 0) {
        nearbyStreets = parsed;
      }
    }
  } catch (e) { console.error("Nearby streets error:", e.message); }

  // Fallback if Claude fails
  if (nearbyStreets.length === 0) nearbyStreets = [primaryStreet];

  return res.json({
    street: primaryStreet,
    borough, neighborhood, city, label,
    lat: parseFloat(lat), lng: parseFloat(lng),
    isGPS: true,
    nearbyStreets,
  });
});

// Helper: get next N upcoming dates for given day abbreviations
function getUpcomingDates(days, weeksAhead = 2) {
  const dayIndex = { Sun:0, Mon:1, Tue:2, Wed:3, Thu:4, Fri:5, Sat:6 };
  const today = new Date();
  today.setHours(0,0,0,0);
  const dates = [];
  for (let i = 0; i <= weeksAhead * 7; i++) {
    const d = new Date(today);
    d.setDate(today.getDate() + i);
    const abbr = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][d.getDay()];
    if (days.includes(abbr)) {
      dates.push(d.toLocaleDateString("en-US", { weekday:"short", month:"short", day:"numeric" }));
    }
  }
  return dates.slice(0, 6); // next 6 occurrences
}
app.get("/api/cleaning", async (req, res) => {
  const { street, lat, lng, borough } = req.query;
  if (!street) return res.json([]);

  try {
    const locationCtx = lat && lng ? `at approximately lat=${lat}, lng=${lng}` : `in ${borough || "the city"}`;
    const text = await askClaude(`You are a US alternate side parking and street cleaning expert. Return ONLY a raw JSON array, no other text.

Street: "${street}" ${locationCtx}

Determine which city this street is in based on coordinates or context, then return accurate street cleaning schedules.

CITY PATTERNS:
- NYC (Manhattan): Mon+Thu OR Tue+Fri, typically 8-9:30AM or 8:30-10AM or 11:30AM-1PM
- NYC (Brooklyn/Queens/Bronx): Mon+Thu OR Tue+Fri, similar times, some areas Sat
- Los Angeles: typically once/week per side, Mon-Sat between 8AM-6PM varies by zone
- Chicago: typically once/week per side, 7AM-9AM or 9AM-12PM varies by neighborhood
- San Francisco: typically once/week per side, 8AM-9AM or 10AM-12PM varies by block
- Boston: typically once/week, 8AM-11AM varies by neighborhood
- Philadelphia: typically once/week per side, 8AM-9:30AM varies by zone
- Washington DC: typically once/week per side, 7:30AM-9:30AM or 9:30AM-11AM
- Seattle: typically once/week per side, 8AM-10AM varies by zone

Rules:
- Return a JSON array of cleaning schedules
- If unknown, return exactly: []
- Do NOT write any explanation, preamble, or prose
- Start your response with [ and end with ]

Each item: {"days":["Mon","Thu"],"time":"8 AM - 9:30 AM","side":"Left / Even side","raw":"NO PARKING 8AM-9:30AM MON & THUR"}

Respond with ONLY the JSON array starting with [:`);

    // Extract JSON array even if Claude added any surrounding text
    const match = text.match(/\[[\s\S]*\]/);
    if (match) {
      const schedule = JSON.parse(match[0]);
      if (Array.isArray(schedule) && schedule.length > 0) {
        return res.json(schedule.map(s => ({ ...s, upcomingDates: getUpcomingDates(s.days || []) })));
      }
    }
  } catch (e) { console.error("Claude cleaning error:", e.message); }

  // DOT Socrata fallback
  try {
    const name = street.toUpperCase().trim();
    const r = await fetch(`${SOCRATA}/xswq-wnv9.json?$where=upper(street)%20LIKE%20'%25${encodeURIComponent(name)}%25'&$limit=200`);
    if (r.ok) {
      const raw = await r.json();
      const results = raw.map(row => {
        const parsed = parseSignText(row.signdesc || row.description || "");
        if (!parsed || !parsed.days.length) return null;
        return { street: row.street || name, side: row.side_of_street || "", days: parsed.days, time: parsed.time, raw: parsed.raw, upcomingDates: getUpcomingDates(parsed.days) };
      }).filter(Boolean);
      return res.json(dedupe(results));
    }
  } catch (e) { console.error("DOT fallback error:", e.message); }

  res.json([]);
});

// ─── BATCH CLEANING (for neighborhoods/zips — one Claude call for many streets) ─
app.get("/api/cleaning-batch", async (req, res) => {
  const { streets: streetsParam, lat, lng, borough } = req.query;
  if (!streetsParam) return res.json({});

  const streets = streetsParam.split(",").map(s => s.trim()).filter(Boolean).slice(0, 30);
  const locationCtx = lat && lng ? `near lat ${lat}, lng ${lng}` : `in ${borough || "the city"}`;

  try {
    const text = await askClaude(`You are a US alternate side parking expert covering NYC, LA, Chicago, SF, Boston, Philadelphia, DC, and Seattle. Return cleaning schedules for ALL these streets ${locationCtx}:

${streets.map((s, i) => `${i+1}. ${s}`).join("\n")}

Determine the city from coordinates or context, then return accurate schedules.
Return ONLY a JSON object where each key is the EXACT street name and value is an array of schedules.
If unknown use [].

{"BEDFORD AVENUE": [{"days":["Mon","Thu"],"time":"8 AM - 9:30 AM","side":"","raw":"NO PARKING 8AM-9:30AM MON & THUR"}], "BERRY STREET": []}

Return ONLY the JSON object starting with {:`, 3000);

    const match = text.match(/\{[\s\S]*\}/);
    if (match) {
      const data = JSON.parse(match[0]);
      // Add upcoming dates to each result
      const result = {};
      for (const [street, schedules] of Object.entries(data)) {
        result[street] = (schedules || []).map(s => ({ ...s, upcomingDates: getUpcomingDates(s.days || []) }));
      }
      return res.json(result);
    }
  } catch(e) { console.error("Batch cleaning error:", e.message); }

  res.json({});
});
// ─── HEATMAP CACHE ───────────────────────────────────────────────────────────
const heatmapCache = new Map();
const CACHE_TTL = 10 * 60 * 1000; // 10 minutes

// ─── PARKING HEAT MAP — real street geometries from OpenStreetMap ─────────────
app.get("/api/heatmap", async (req, res) => {
  const { lat, lng } = req.query;
  if (!lat || !lng) return res.json([]);

  // Round to 3 decimal places (~100m grid) for cache key
  const cacheKey = `${parseFloat(lat).toFixed(3)},${parseFloat(lng).toFixed(3)}`;
  const cached = heatmapCache.get(cacheKey);
  if (cached && Date.now() - cached.ts < CACHE_TTL) {
    console.log(`Heatmap cache hit: ${cacheKey}`);
    return res.json(cached.data);
  }

  try {
    // Step 1: Get real street geometries from Overpass API
    const overpassQuery = `[out:json][timeout:15];way(around:400,${lat},${lng})["highway"~"^(residential|secondary|tertiary|primary|unclassified|living_street)$"]["name"];out geom;`;
    const r = await fetch(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(overpassQuery)}`, { headers: { "User-Agent": "StreetParkInfo/1.0" } });
    if (!r.ok) return res.json([]);
    const data = await r.json();
    const ways = (data.elements || []).filter(w => w.tags?.name && w.geometry?.length > 1);

    // Step 2: Get unique street names
    const streetNames = [...new Set(ways.map(w => w.tags.name.toUpperCase()))].slice(0, 20);
    if (!streetNames.length) return res.json([]);

    // Step 3: One Claude call for all schedules
    const schedulesRaw = await askClaude(`NYC alternate side parking schedules near lat=${lat}, lng=${lng}.

Streets:
${streetNames.map((s,i) => `${i+1}. ${s}`).join("\n")}

Return ONLY a JSON object. Key = street name in CAPS, value = array of schedules (empty array if unknown).
{"BEDFORD AVENUE":[{"days":["Mon","Thu"],"time":"8 AM - 9:30 AM"}],"BERRY STREET":[]}
Return ONLY the JSON object:`, 2000);

    let schedules = {};
    try { const m = schedulesRaw.match(/\{[\s\S]*\}/); if (m) schedules = JSON.parse(m[0]); } catch(e) {}

    const today    = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][new Date().getDay()];
    const tomorrow = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][new Date(Date.now()+86400000).getDay()];
    const in2days  = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][new Date(Date.now()+172800000).getDay()];
    const in3days  = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][new Date(Date.now()+259200000).getDay()];

    // Step 4: Merge real geometry with schedule urgency — keep ALL segments
    const result = ways.map(w => {
        const name = w.tags.name.toUpperCase();
        const sch = schedules[name] || [];
        const coords = w.geometry.map(p => [p.lat, p.lon]);
        let urgency = sch.length ? "green" : "gray";
        let nextClean = null;
        for (const s of sch) {
          const days = s.days || [];
          if (days.includes(today))    { urgency = "red";    nextClean = `Today ${s.time||""}`.trim(); break; }
          if (days.includes(tomorrow)) { urgency = "red";    nextClean = `Tomorrow ${s.time||""}`.trim(); break; }
          if (days.includes(in2days) || days.includes(in3days)) {
            if (urgency !== "red") { urgency = "yellow"; nextClean = `In 2-3 days ${s.time||""}`.trim(); }
          }
        }
        return { street: name, coords, urgency, nextClean };
      });

    heatmapCache.set(cacheKey, { data: result, ts: Date.now() });
    res.json(result);
  } catch(e) { console.error("Heatmap error:", e.message); res.json([]); }
});
// Strategy: search by street name fragments, nearby cross streets, and borough-wide
// NYC Open Data dataset tg4x-b46p is the official Mayor's Office of Media & Entertainment permits
app.get("/api/films", async (req, res) => {
  const { street, borough, lat, lng } = req.query;
  const from = new Date(); from.setDate(from.getDate() - 1);
  const to   = new Date(); to.setDate(to.getDate() + 21); // 3 weeks out
  const fmt  = d => d.toISOString().split(".")[0];
  const dateFilter = `startdatetime >= '${fmt(from)}' AND startdatetime <= '${fmt(to)}'`;

  const results = new Map(); // dedupe by eventid

  const addResults = (permits) => {
    permits.forEach(f => {
      if (!results.has(f.eventid)) {
        results.set(f.eventid, {
          id:          f.eventid,
          type:        f.category || "Film/TV",
          subtype:     f.subcategoryname || f.eventtype || f.zipcode_s || "Production",
          start:       f.startdatetime,
          end:         f.enddatetime,
          parkingHeld: f.parkingheld || "",
          borough:     f.borough || "",
          address:     f.address || "",
          country:     f.country || "",
        });
      }
    });
  };

  try {
    // Search 1: exact street name in parkingheld field
    if (street) {
      const name = street.toUpperCase().trim();
      // Try multiple variations of the street name
      const variants = [name];
      // "WEST 46 STREET" → also try "W 46", "46TH", "46 ST"
      const numMatch = name.match(/^(WEST|EAST|NORTH|SOUTH)?\s*(\d+)\s*(STREET|AVENUE|BOULEVARD|DRIVE|PLACE|ROAD)?$/i);
      if (numMatch) {
        const num = numMatch[2];
        variants.push(num + " ST", num + "TH", num + "ND", num + "RD", "W " + num, "E " + num);
      }
      // Also strip directional prefix for broad match
      const stripped = name.replace(/^(WEST|EAST|NORTH|SOUTH)\s+/i, "");
      if (stripped !== name) variants.push(stripped);

      for (const v of variants) {
        const encoded = encodeURIComponent(v);
        const url = `${SOCRATA}/tg4x-b46p.json?$where=upper(parkingheld)%20LIKE%20'%25${encoded}%25'%20AND%20${dateFilter}&$limit=50&$order=startdatetime%20ASC`;
        const r = await fetch(url);
        if (r.ok) addResults(await r.json());
      }
    }

    // Search 2: borough-wide recent/upcoming permits (catches everything nearby)
    if (borough) {
      const boroughMap = {
        "manhattan": "Manhattan", "brooklyn": "Brooklyn", "queens": "Queens",
        "bronx": "Bronx", "the bronx": "Bronx", "staten island": "Staten Island"
      };
      const boroughNorm = boroughMap[borough.toLowerCase()] || borough;
      const encoded = encodeURIComponent(boroughNorm.toUpperCase());
      const url = `${SOCRATA}/tg4x-b46p.json?$where=upper(borough)%20LIKE%20'%25${encoded}%25'%20AND%20${dateFilter}&$limit=100&$order=startdatetime%20ASC`;
      const r = await fetch(url);
      if (r.ok) addResults(await r.json());
    }

    // Search 3: if we have coordinates, also search by zip code area
    // The dataset has zipcode_s field
    if (lat && lng) {
      // Round to ~0.5 mile bounding box
      const latD = 0.007, lngD = 0.009;
      const latMin = parseFloat(lat) - latD, latMax = parseFloat(lat) + latD;
      const lngMin = parseFloat(lng) - lngD, lngMax = parseFloat(lng) + lngD;
      // Can't query by coords directly but we can get all current borough permits (already done above)
      // So this is a no-op if borough was provided
    }

    const all = Array.from(results.values())
      .sort((a, b) => new Date(a.start) - new Date(b.start));

    res.json(all);
  } catch (e) {
    console.error("Films error:", e.message);
    res.json([]);
  }
});

// ─── PUBLIC EVENTS ────────────────────────────────────────────────────────────
app.get("/api/events", async (req, res) => {
  const { borough } = req.query;
  const today = new Date().toISOString().split("T")[0];
  const toDate = new Date(); toDate.setDate(toDate.getDate()+14);
  try {
    const bf = borough ? `%20AND%20upper(borough)%20LIKE%20'%25${encodeURIComponent(borough.toUpperCase())}%25'` : "";
    const url = `${SOCRATA}/tvpp-9vvx.json?$where=startdate%20>=%20'${today}'%20AND%20startdate%20<=%20'${toDate.toISOString().split("T")[0]}'${bf}&$limit=15&$order=startdate%20ASC`;
    const r = await fetch(url);
    if (!r.ok) return res.json([]);
    res.json((await r.json()).map(ev => ({ name:ev.eventname||ev.name||"City Event", type:ev.eventtype||"Event", start:ev.startdate, location:ev.eventlocation||"", borough:ev.borough||"", parkingImpacted:!!(ev.parkingimpacted) })));
  } catch { res.json([]); }
});

// ─── WEATHER ──────────────────────────────────────────────────────────────────
app.get("/api/weather", async (req, res) => {
  const { lat, lng } = req.query;
  if (!lat || !lng) return res.json(null);
  try {
    const url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,weather_code,wind_speed_10m,precipitation&daily=weather_code,precipitation_sum,snowfall_sum&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&forecast_days=3&timezone=America%2FNew_York`;
    const r = await fetch(url);
    res.json(r.ok ? await r.json() : null);
  } catch { res.json(null); }
});

// ─── ASP STATUS ───────────────────────────────────────────────────────────────
app.get("/api/asp", async (req, res) => {
  try {
    const today = new Date().toLocaleDateString("en-CA");
    const r = await fetch(`https://api.nyc.gov/public/api/GetCalendar?calendarTypes=AltSideParking&startDate=${today}&endDate=${today}`);
    if (r.ok) return res.json({ suspended: JSON.stringify(await r.json()).toLowerCase().includes("suspended") });
  } catch (e) { console.error("ASP error:", e.message); }
  res.json({ suspended: false });
});

// ─── AUTH ─────────────────────────────────────────────────────────────────────
// Email signup
app.post("/auth/signup", async (req, res) => {
  const { email, password, name } = req.body;
  if (!email || !password) return res.status(400).json({ error: "Email and password required" });
  try {
    const hash = crypto.createHash("sha256").update(password + JWT_SECRET).digest("hex");
    const tier = email.toLowerCase() === "bassklaft@gmail.com" ? "unlimited" : "free";
    const { rows } = await db.query(
      `INSERT INTO users (email, password_hash, name, tier) VALUES ($1, $2, $3, $4) 
       ON CONFLICT (email) DO NOTHING RETURNING id, email, name, tier, search_count`,
      [email.toLowerCase(), hash, name || email.split("@")[0], tier]
    );
    if (!rows.length) return res.status(409).json({ error: "Email already registered" });
    const user = rows[0];
    const token = signToken({ userId: user.id, tier: user.tier });
    res.json({ token, user: { id: user.id, email: user.email, name: user.name, tier: user.tier, searchCount: user.search_count } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// Email login
app.post("/auth/login", async (req, res) => {
  const { email, password } = req.body;
  if (!email || !password) return res.status(400).json({ error: "Email and password required" });
  try {
    const hash = crypto.createHash("sha256").update(password + JWT_SECRET).digest("hex");
    // Always ensure bassklaft@gmail.com has unlimited tier
    if (email.toLowerCase() === "bassklaft@gmail.com") {
      await db.query(`UPDATE users SET tier='unlimited' WHERE email=$1`, [email.toLowerCase()]).catch(() => {});
    }
    const { rows } = await db.query(
      `UPDATE users SET last_seen=NOW() WHERE email=$1 AND password_hash=$2 AND active=true RETURNING id, email, name, tier, search_count`,
      [email.toLowerCase(), hash]
    );
    if (!rows.length) return res.status(401).json({ error: "Invalid email or password" });
    const user = rows[0];
    const token = signToken({ userId: user.id, tier: user.tier });
    res.json({ token, user: { id: user.id, email: user.email, name: user.name, tier: user.tier, searchCount: user.search_count } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// Apple Sign In
app.post("/auth/apple", async (req, res) => {
  const { appleId, email, name } = req.body;
  if (!appleId) return res.status(400).json({ error: "Apple ID required" });
  try {
    const { rows } = await db.query(
      `INSERT INTO users (apple_id, email, name, tier) VALUES ($1, $2, $3, 'free')
       ON CONFLICT (apple_id) DO UPDATE SET last_seen=NOW(), email=COALESCE(EXCLUDED.email, users.email), name=COALESCE(EXCLUDED.name, users.name)
       RETURNING id, email, name, tier, search_count`,
      [appleId, email || null, name || "Apple User"]
    );
    const user = rows[0];
    const token = signToken({ userId: user.id, tier: user.tier });
    res.json({ token, user: { id: user.id, email: user.email, name: user.name, tier: user.tier, searchCount: user.search_count } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// Get current user
app.get("/auth/me", authMiddleware, async (req, res) => {
  try {
    const { rows } = await db.query(
      "SELECT id, email, name, tier, search_count FROM users WHERE id=$1",
      [req.userId]
    );
    if (!rows.length) return res.status(404).json({ error: "User not found" });
    res.json({ user: { ...rows[0], searchCount: rows[0].search_count } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// Track a search/interaction
app.post("/auth/track", authMiddleware, async (req, res) => {
  const { lat, lng, label, locData } = req.body;
  try {
    const { rows } = await db.query(
      `UPDATE users SET search_count=search_count+1, last_seen=NOW() WHERE id=$1 RETURNING search_count, tier`,
      [req.userId]
    );
    const { search_count, tier } = rows[0];
    const limit = TIER_LIMITS[tier]?.searches || 8;
    const exceeded = tier === "free" && search_count > limit;

    // Save to recent searches (keep last 2)
    if (lat && lng) {
      await db.query(
        `INSERT INTO recent_searches (user_id, label, lat, lng, loc_data) VALUES ($1,$2,$3,$4,$5)`,
        [req.userId, label, lat, lng, JSON.stringify(locData || {})]
      );
      await db.query(
        `DELETE FROM recent_searches WHERE user_id=$1 AND id NOT IN (SELECT id FROM recent_searches WHERE user_id=$1 ORDER BY searched_at DESC LIMIT 2)`,
        [req.userId]
      );
    }

    res.json({ searchCount: search_count, exceeded, tier, limit });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// Get recent searches (for map pins)
app.get("/auth/recent", authMiddleware, async (req, res) => {
  try {
    const { rows } = await db.query(
      `SELECT label, lat, lng, loc_data FROM recent_searches WHERE user_id=$1 ORDER BY searched_at DESC LIMIT 2`,
      [req.userId]
    );
    res.json(rows);
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// ─── SAVED SEARCHES (Unlimited+Save tier only) ────────────────────────────────
app.get("/saved-searches", authMiddleware, async (req, res) => {
  try {
    const { rows } = await db.query(
      `SELECT id, label, street, lat, lng, borough, neighborhood, city, loc_data, checked FROM saved_searches WHERE user_id=$1 ORDER BY created_at DESC`,
      [req.userId]
    );
    res.json(rows);
  } catch(e) { res.status(500).json({ error: e.message }); }
});

app.post("/saved-searches", authMiddleware, async (req, res) => {
  const { label, street, lat, lng, borough, neighborhood, city, locData } = req.body;
  try {
    // Check tier
    const { rows: user } = await db.query("SELECT tier FROM users WHERE id=$1", [req.userId]);
    if (user[0]?.tier !== "unlimited") return res.status(403).json({ error: "Upgrade to Unlimited+Save to save searches" });
    // Check limit
    const { rows: count } = await db.query("SELECT COUNT(*) FROM saved_searches WHERE user_id=$1", [req.userId]);
    if (parseInt(count[0].count) >= 10) return res.status(400).json({ error: "Maximum 10 saved searches. Uncheck one to make room." });
    const { rows } = await db.query(
      `INSERT INTO saved_searches (user_id, label, street, lat, lng, borough, neighborhood, city, loc_data) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,
      [req.userId, label, street, lat, lng, borough, neighborhood, city, JSON.stringify(locData || {})]
    );
    res.json(rows[0]);
  } catch(e) { res.status(500).json({ error: e.message }); }
});

app.patch("/saved-searches/:id", authMiddleware, async (req, res) => {
  const { checked } = req.body;
  try {
    await db.query(
      `UPDATE saved_searches SET checked=$1 WHERE id=$2 AND user_id=$3`,
      [checked, req.params.id, req.userId]
    );
    // Delete unchecked ones (they shouldn't persist)
    await db.query(`DELETE FROM saved_searches WHERE user_id=$1 AND checked=false`, [req.userId]);
    res.json({ ok: true });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

app.delete("/saved-searches/:id", authMiddleware, async (req, res) => {
  try {
    await db.query(`DELETE FROM saved_searches WHERE id=$1 AND user_id=$2`, [req.params.id, req.userId]);
    res.json({ ok: true });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// ─── SUBSCRIBE ────────────────────────────────────────────────────────────────
app.post("/subscribe", async (req, res) => {
  const { phone, street, borough, lat, lng } = req.body;
  if (!phone || !street) return res.status(400).json({ error: "phone and street required" });
  const digits = phone.replace(/\D/g,"");
  const e164 = digits.startsWith("1") ? `+${digits}` : `+1${digits}`;
  try {
    await db.query(`INSERT INTO subscribers (phone,street,borough,lat,lng) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (phone) DO UPDATE SET street=$2,borough=$3,lat=$4,lng=$5,active=true`, [e164,street.toUpperCase(),borough||"",lat||null,lng||null]);
    await twilioClient.messages.create({ body:`🚗 Street Park Now activated for ${street}! We'll text you before street cleaning, film shoots, and bad weather. Reply STOP to cancel.`, from:process.env.TWILIO_PHONE_NUMBER, to:e164 });
    res.json({ ok: true });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ─── STRIPE ───────────────────────────────────────────────────────────────────
app.post("/create-checkout-session", async (req, res) => {
  const { plan, userId, email } = req.body;
  const PRICES = {
    "basic-monthly":     process.env.STRIPE_PRICE_BASIC_MONTHLY,
    "basic-annual":      process.env.STRIPE_PRICE_BASIC_ANNUAL,
    "premium-monthly":   process.env.STRIPE_PRICE_PREMIUM_MONTHLY,
    "premium-annual":    process.env.STRIPE_PRICE_PREMIUM_ANNUAL,
    "unlimited-monthly": process.env.STRIPE_PRICE_UNLIMITED_MONTHLY,
    "unlimited-annual":  process.env.STRIPE_PRICE_UNLIMITED_ANNUAL,
    // Legacy
    "monthly": process.env.STRIPE_PRICE_BASIC_MONTHLY,
    "annual":  process.env.STRIPE_PRICE_BASIC_ANNUAL,
  };
  const priceId = PRICES[plan];
  if (!priceId) return res.status(400).json({ error: "Invalid plan" });
  try {
    const session = await stripe.checkout.sessions.create({
      payment_method_types: ["card"],
      mode: "subscription",
      line_items: [{ price: priceId, quantity: 1 }],
      metadata: { userId: userId || "", plan },
      customer_email: email || undefined,
      success_url: `${process.env.FRONTEND_URL}?subscribed=true&plan=${plan}`,
      cancel_url: process.env.FRONTEND_URL,
    });
    res.json({ url: session.url });
  } catch(err) { res.status(500).json({ error: err.message }); }
});

app.post("/webhook", async (req, res) => {
  let event;
  try { event = stripe.webhooks.constructEvent(req.body, req.headers["stripe-signature"], process.env.STRIPE_WEBHOOK_SECRET); }
  catch (err) { return res.status(400).send(`Webhook Error: ${err.message}`); }

  if (event.type === "checkout.session.completed") {
    const session = event.data.object;
    const { userId, plan } = session.metadata || {};
    const tier = plan?.includes("unlimited") ? "unlimited" : plan?.includes("premium") ? "premium" : "basic";
    if (userId) {
      await db.query(
        `UPDATE users SET tier=$1, stripe_customer_id=$2, stripe_subscription_id=$3, stripe_price_id=$4 WHERE id=$5`,
        [tier, session.customer, session.subscription, plan, userId]
      ).catch(console.error);
    }
    // Also update legacy subscribers table
    await db.query(
      `UPDATE subscribers SET stripe_customer_id=$1, stripe_subscription_id=$2, plan=$3, active=true WHERE phone=$4`,
      [session.customer, session.subscription, tier, session.metadata?.phone || ""]
    ).catch(() => {});
  }

  if (event.type === "customer.subscription.deleted") {
    await db.query(
      `UPDATE users SET tier='free' WHERE stripe_subscription_id=$1`,
      [event.data.object.id]
    ).catch(console.error);
    await db.query("UPDATE subscribers SET active=false WHERE stripe_subscription_id=$1", [event.data.object.id]).catch(console.error);
  }

  res.json({ received: true });
});

// ─── NIGHTLY ALERTS ───────────────────────────────────────────────────────────
async function sendNightlyAlerts() {
  const { rows: subs } = await db.query("SELECT * FROM subscribers WHERE active=true");
  const tomorrow = new Date(); tomorrow.setDate(tomorrow.getDate()+1);
  const tomorrowAbbr = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][tomorrow.getDay()];
  const tomorrowStr = tomorrow.toLocaleDateString("en-US",{ weekday:"long", month:"long", day:"numeric" });
  for (const sub of subs) {
    const msgs = [];
    try {
      const base = `http://localhost:${PORT}`;
      const [cResp,fResp,wxResp] = await Promise.allSettled([
        fetch(`${base}/api/cleaning?street=${encodeURIComponent(sub.street)}&lat=${sub.lat}&lng=${sub.lng}`).then(r=>r.json()),
        fetch(`${base}/api/films?street=${encodeURIComponent(sub.street)}`).then(r=>r.json()),
        fetch(`${base}/api/weather?lat=${sub.lat}&lng=${sub.lng}`).then(r=>r.json()),
      ]);
      const cleaning = cResp.status==="fulfilled" ? cResp.value : [];
      const films = fResp.status==="fulfilled" ? fResp.value : [];
      const wx = wxResp.status==="fulfilled" ? wxResp.value : null;
      const cleanTomorrow = cleaning.find(c=>c.days?.includes(tomorrowAbbr));
      if (cleanTomorrow) msgs.push(`🧹 Street cleaning on ${sub.street} tomorrow${cleanTomorrow.time ? ` from ${cleanTomorrow.time}` : ""}. Move your car!`);
      if (films.length) msgs.push(`🎬 Film shoot near ${sub.street} — parking may be restricted.`);
      const code=wx?.daily?.weather_code?.[1], snow=wx?.daily?.snowfall_sum?.[1], rain=wx?.daily?.precipitation_sum?.[1];
      if ([71,73,75,77,85,86].includes(code)&&snow>0.5) msgs.push(`❄️ Snow tomorrow (${snow.toFixed(1)}"). Move your car early.`);
      else if ([61,63,65,80,81,82].includes(code)&&rain>0.5) msgs.push(`🌧️ Heavy rain tomorrow. Street cleaning may still be enforced.`);
      else if ([95,96,99].includes(code)) msgs.push(`⛈️ Thunderstorms tomorrow. Check parking rules.`);
      if (msgs.length) await twilioClient.messages.create({ body:`Street Park Now — ${tomorrowStr}:\n\n${msgs.join("\n\n")}\n\nReply STOP to cancel.`, from:process.env.TWILIO_PHONE_NUMBER, to:sub.phone });
    } catch (err) { console.error(`Alert failed for ${sub.phone}:`, err.message); }
    await new Promise(r=>setTimeout(r,150));
  }
  console.log(`✅ Alerts done for ${subs.length} subscribers`);
}

cron.schedule("0 20 * * *", sendNightlyAlerts, { timezone: "America/New_York" });
cron.schedule("*/14 * * * *", () => { fetch(`https://${process.env.RENDER_SERVICE_URL||`localhost:${PORT}`}/health`).catch(()=>{}); });
app.post("/admin/trigger-alerts", async (req,res) => { if(req.body.secret!==process.env.ADMIN_SECRET) return res.status(401).json({error:"unauthorized"}); sendNightlyAlerts().catch(console.error); res.json({ok:true}); });

// ─── DB + START ────────────────────────────────────────────────────────────────
async function initDB() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS subscribers (
      id SERIAL PRIMARY KEY, phone TEXT NOT NULL UNIQUE, street TEXT NOT NULL,
      borough TEXT DEFAULT '', lat DOUBLE PRECISION, lng DOUBLE PRECISION,
      stripe_customer_id TEXT, stripe_subscription_id TEXT,
      plan TEXT DEFAULT 'trial', trial_ends_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '30 days',
      active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS alert_log (
      id SERIAL PRIMARY KEY, subscriber_id INTEGER REFERENCES subscribers(id),
      message TEXT, sent_at TIMESTAMPTZ DEFAULT NOW(), type TEXT
    );
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      email TEXT UNIQUE,
      password_hash TEXT,
      apple_id TEXT UNIQUE,
      name TEXT,
      tier TEXT DEFAULT 'free',
      search_count INTEGER DEFAULT 0,
      stripe_customer_id TEXT,
      stripe_subscription_id TEXT,
      stripe_price_id TEXT,
      active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      last_seen TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS saved_searches (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      label TEXT NOT NULL,
      street TEXT,
      lat DOUBLE PRECISION,
      lng DOUBLE PRECISION,
      borough TEXT,
      neighborhood TEXT,
      city TEXT,
      loc_data JSONB,
      checked BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS recent_searches (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      label TEXT,
      lat DOUBLE PRECISION,
      lng DOUBLE PRECISION,
      loc_data JSONB,
      searched_at TIMESTAMPTZ DEFAULT NOW()
    );
  `);
  console.log("✅ DB ready");
}

initDB().then(() => app.listen(PORT, () => console.log(`🚗 Street Park Now running on port ${PORT}`)));
